AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - 'validator.gemspec'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Lint/Debugger:
  Enabled: true
